jobs:
  test:
    docker:
      - image: 'cimg/node:16.3.0-browsers'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: Test
          command: npm test
      - store_test_results:
          path: allure-report
orbs:
  browser-tools: circleci/browser-tools@1.1.3
version: 2.1
workflows:
  version: 2.1
  test:
    jobs:
      - test
