jobs:
  test:
    docker:
      - image: 'cimg/node:13.12-browser'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
orbs:
  browser-tools: circleci/browser-tools@1.1.3
version: 2.1
workflows:
  version: 2.1
  test:
    jobs:
      - test
